FROM golang:1.18-bullseye

WORKDIR /app

COPY . ./

RUN apt-get update
RUN apt-get install -y protobuf-compiler 
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
RUN export PATH="$PATH:$(go env GOPATH)/bin"

RUN go mod download

RUN chmod +x ./pipeline.sh

RUN ./pipeline.sh

EXPOSE 3333

ENTRYPOINT ["./rest"]

# docker build -f dockerfile-rest --tag docker-payments-format-parser-rest .
# sudo docker run -v=$(pwd):/host/root -p 127.0.0.1:3333:3333 docker-payments-format-parser-rest

